global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:
  - job_name: "kamailio_exporter"
    static_configs:
      - targets: ["kamailio_exporter:9494"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
